global:
  scrape_interval: 15s

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: postgres-exporter
    static_configs:
      - targets:
          - postgres-exporter:9187

  - job_name: spring-boot
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - spring-boot-app-1:8080
          - spring-boot-app-2:8080
        labels:
          application: spring-boot-apps
#rule_files:
#  - alert_rules.yml
