version: '2.4'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - monitor

networks:
  monitor:
    external: true
    name: monitor-net
