version: "2.4"
services:
  postgres-exporter:
    container_name: postgres-exporter
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_URI: host.docker.internal:5432/postgres?sslmode=disable
      DATA_SOURCE_USER: postgres
      DATA_SOURCE_PASS: pro123
    ports:
      - 9187:9187
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - monitor

networks:
  monitor:
    external: true
    name: monitor-net
